spring:
    # nacos服务配置
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.0.114:8848
                ip: 192.168.1.108
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://rm-m5e277z772hwom5t6jo.mysql.rds.aliyuncs.com:3306/fast?serverTimezone=GMT&useSSL=false
        username: root
        password: Dobi624dobi624
#        url: jdbc:mysql://rm-m5e8r75zz97048wqp3o.mysql.rds.aliyuncs.com:3306/fast?serverTimezone=GMT&useSSL=false
        sql-script-encoding: UTF-8
        platform: mysql
#    redis:
#        #Redis数据库索引（默认为0）
#        database: 0
#        host: 47.110.251.3
#        port: 6379
#        password: dobi624
#        #连接超时时间（毫秒）
#        timeout: 5000
#        pool:
#            #连接池最大连接数（使用负值表示没有限制）
#            max-active: 8
#            #连接池最大阻塞等待时间（使用负值表示没有限制）
#            max-wait: -1
#            #连接池中最大空闲连接
#            max-idle: 8
#            #连接池中最小空闲连接
#            min-idle: 1
swagger:
    show: true
    package: com.cloud.fast.controller
    title: 快速单品综合服务接口文档
    version: 1.0
    name: 梦一线间
    url:
    email: xjpdyx@hotmail.com
    description: 快速单品综合服务接口文档
file:
    domain: http://file.cwmz.top/
#    server: /root/java/fast/
    server: D:\
wx:
    appid:
    secret:
jwt:
    include-path-patterns:
    exclude-path-patterns:
        - /error
        - /swagger-resources
        - /doc.html
        - /webjars/bycdao-ui/**
        - /**
uc:
    domain: http://localhost:8100/
    request:
        user-info: /sysUser/info
        check-permission: /sysPermission/check
        user-open-info: /sysUser/info/open/
# 七牛云
qiniu:
    access-key: eUGhwzBCa0-_H8rr3bbGT6Ov_ry3eXBGL-1YWhFP
    secret-key: T_sGxrouhk1SIH0t98D1Lil5_bJwDEpkN55f0qil
    bucket: dobi
