spring:
    cloud:
        # nacos服务配置
        nacos:
            discovery:
                server-addr: 144.34.143.83:8848
        # 网关配置
        gateway:
            discovery:
                locator:
                    # 开启注册
                    enabled: false
                    lowerCaseServiceId: true
            routes:
                -   id: dobi-admin
                    uri: lb://dobi-admin
                    predicates:
                        - Path=/uc/**
                    filters:
                        - StripPrefix=1
