version: "3"
services:
    dobi-pets:
        image: xjp1070860185/dobi-pets
        ports:
            - "8081:8081"
        networks:
            - webnet
        environment:
            - "SPRING_PROFILES_ACTIVE=prod"
        volumes:
            - /mnt/cloud/:/mnt/cloud/
    dobi-admin:
        image: xjp1070860185/dobi-admin
        ports:
            - "8100:8100"
        networks:
            - webnet
        environment:
            - "SPRING_PROFILES_ACTIVE=prod"
        volumes:
            - /mnt/cloud/:/mnt/cloud/
    dobi-fast:
        image: xjp1070860185/dobi-fast
        ports:
            - "8082:8082"
        networks:
            - webnet
        environment:
            - "SPRING_PROFILES_ACTIVE=prod"
        volumes:
          - /mnt/cloud/:/mnt/cloud/
networks:
    webnet:
