version: "3"
services:
    dobi-gateway:
        image: registry.cn-qingdao.aliyuncs.com/dobi/cloud-gateway
        ports:
            - "8110:8110"
        networks:
            - webnet
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
        volumes:
          - /tmp/cloud/:/tmp/cloud/
#    dobi-pets:
#        image: xjp1070860185/dobi-pets
#        ports:
#            - "8081:8081"
#        networks:
#            - webnet
#        environment:
#            - "SPRING_PROFILES_ACTIVE=prod"
#        volumes:
#            - /mnt/cloud/:/mnt/cloud/
    dobi-admin:
        image: registry.cn-qingdao.aliyuncs.com/dobi/cloud-admin
        ports:
            - "8100:8100"
        networks:
            - webnet
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
        volumes:
            - /tmp/cloud/:/tmp/cloud/
    dobi-fast:
        image: xjp1070860185/dobi-fast
        ports:
            - "8082:8082"
        networks:
            - webnet
        environment:
            - "SPRING_PROFILES_ACTIVE=prod"
        volumes:
            - /mnt/cloud/:/mnt/cloud/
networks:
    webnet:
