spring:
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.0.114:8848
                ip: 192.168.0.135
        gateway:
            discovery:
                locator:
                    enabled: true
                    lowerCaseServiceId: true
            loadbalancer:
                use404: true
#logging:
#    level:
#        root: info
