server:
    port: 8110
spring:
    application:
        name: gateway
    cloud:
        nacos:
            discovery:
                server-addr: 144.34.143.83:8848
        gateway:
            discovery:
                locator:
                    enabled: false
                    lowerCaseServiceId: true
            loadbalancer:
                use404: true
            routes:
                -   id: dobi-admin
                    uri: lb://dobi-admin
                    predicates:
                        - Path=/dobi-admin/**
                    filters:
                        - StripPrefix=1
                -   id: dobi-fast
                    uri: lb://dobi-fast
                    predicates:
                        - Path=/fast/**
                    filters:
                        - StripPrefix=1

