spring:
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
#                ip: 192.168.0.135
        gateway:
            discovery:
                locator:
                    enabled: true
                    lowerCaseServiceId: true
            loadbalancer:
                use404: true
#logging:
#    level:
#        root: info
