spring:
#    cloud:
#        nacos:
#            discovery:
#                server-addr: 144.34.143.83:8848
#                ip: 47.110.251.3
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://rm-m5e277z772hwom5t6jo.mysql.rds.aliyuncs.com:3306/cloud_admin?serverTimezone=GMT
        username: root
        password: Dobi624dobi624
        sql-script-encoding: UTF-8
        platform: mysql
#    redis:
#        #Redis数据库索引（默认为0）
#        database: 0
#        host: 47.110.251.3
#        port: 6379
#        password: dobi624
#        #连接超时时间（毫秒）
#        timeout: 5000
#        pool:
#            #连接池最大连接数（使用负值表示没有限制）
#            max-active: 8
#            #连接池最大阻塞等待时间（使用负值表示没有限制）
#            max-wait: -1
#            #连接池中最大空闲连接
#            max-idle: 8
#            #连接池中最小空闲连接
#            min-idle: 1
swagger:
    show: true
    package: com.cloud.admin.controller
    title: 后台管理系统接口文档
    version: 1.1
    name: 梦一线间
    url:
    email: xjpdyx@hotmail.com
    description: 后台管理系统接口文档
file:
    domain: http://file.cwmz.top/
    server: /mnt/cloud/
wx:
    appid: wx12509072f8865649
    secret: c9313a02e78e085a253a304b64369b24
    lyx:
        appid: wxa4e734c6c2eeb77b
        secret: b56f46b5d1f6696723512dcf99d5ec02
jwt:
    include-path-patterns:
        - /**
    exclude-path-patterns:
        - /error
        - /swagger-resources
        - /doc.html
        - /webjars/bycdao-ui/**
uc:
    domain: http://admin.cwmz.top/
    request:
        user-info: /sysUser/info
        check-permission: /sysPermission/check
        user-open-info: /sysUser/info/open/
dobi:
    admin:
        user: dobi
