spring:
    #    cloud:
    #        nacos:
    #            discovery:
    #                server-addr: 47.110.251.3:8848
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: Dobi123456
        url: jdbc:mysql://rm-m5e8r75zz97048wqp.mysql.rds.aliyuncs.com:3306/pets?serverTimezone=GMT
        sql-script-encoding: UTF-8
        platform: mysql
#    redis:
#        #Redis数据库索引（默认为0）
#        database: 0
#        host: 47.110.251.3
#        port: 6379
#        password: dobi624
#        #连接超时时间（毫秒）
#        timeout: 5000
#        pool:
#            #连接池最大连接数（使用负值表示没有限制）
#            max-active: 8
#            #连接池最大阻塞等待时间（使用负值表示没有限制）
#            max-wait: -1
#            #连接池中最大空闲连接
#            max-idle: 8
#            #连接池中最小空闲连接
#            min-idle: 1
swagger:
    show: false
    package: com.cloud.admin.controller
    title: 后台管理系统接口文档
    version: 1.0
    name: 梦一线间
    url:
    email: xjpdyx@hotmail.com
    description: 后台管理系统接口文档
file:
    server: /root/java/admin/
wx:
    appid:
    secret:
jwt:
    include-path-patterns: /**
    exclude-path-patterns: /swagger-resources, /**
uc:
    domain: http://localhost:8100/
    request:
        user-info: /sysUser/info
        check-permission: /sysPermission/check
